# Basic
title: www.ndxbn.tokyo title
description: www contents of ndxbn.tokyo site.
url: https://www.ndxbn.tokyo
twitter_username: ndxbn
github_username: ndxbn

# For Atom Feed
domain: www.ndxbn.tokyo
author: ndxbn
email: sitri.ndxbn@gmail.com

# Jekyll
timezone: Asia/Tokyo
future: false
markdown: kramdown
kramdown:
  input: GFM

## Template
highlighter: rouge
